#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Thu3")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQLNhanVien(QLNhanVien instance);
    partial void UpdateQLNhanVien(QLNhanVien instance);
    partial void DeleteQLNhanVien(QLNhanVien instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::MiniProject.Properties.Settings.Default.Thu3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QLNhanVien> QLNhanViens
		{
			get
			{
				return this.GetTable<QLNhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLNhanVien")]
	public partial class QLNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tên;
		
		private string _Phòng;
		
		private System.Nullable<int> _LươngperHour;
		
		private System.Nullable<int> _Tuổi;
		
		private System.Nullable<int> _HourWork;
		
		private string _TypeofEmployee;
		
		private string _Cua_Hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTênChanging(string value);
    partial void OnTênChanged();
    partial void OnPhòngChanging(string value);
    partial void OnPhòngChanged();
    partial void OnLươngperHourChanging(System.Nullable<int> value);
    partial void OnLươngperHourChanged();
    partial void OnTuổiChanging(System.Nullable<int> value);
    partial void OnTuổiChanged();
    partial void OnHourWorkChanging(System.Nullable<int> value);
    partial void OnHourWorkChanged();
    partial void OnTypeofEmployeeChanging(string value);
    partial void OnTypeofEmployeeChanged();
    partial void OnCua_HangChanging(string value);
    partial void OnCua_HangChanged();
    #endregion
		
		public QLNhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tên", DbType="NChar(10)")]
		public string Tên
		{
			get
			{
				return this._Tên;
			}
			set
			{
				if ((this._Tên != value))
				{
					this.OnTênChanging(value);
					this.SendPropertyChanging();
					this._Tên = value;
					this.SendPropertyChanged("Tên");
					this.OnTênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phòng", DbType="NChar(10)")]
		public string Phòng
		{
			get
			{
				return this._Phòng;
			}
			set
			{
				if ((this._Phòng != value))
				{
					this.OnPhòngChanging(value);
					this.SendPropertyChanging();
					this._Phòng = value;
					this.SendPropertyChanged("Phòng");
					this.OnPhòngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LươngperHour", DbType="Int")]
		public System.Nullable<int> LươngperHour
		{
			get
			{
				return this._LươngperHour;
			}
			set
			{
				if ((this._LươngperHour != value))
				{
					this.OnLươngperHourChanging(value);
					this.SendPropertyChanging();
					this._LươngperHour = value;
					this.SendPropertyChanged("LươngperHour");
					this.OnLươngperHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuổi", DbType="Int")]
		public System.Nullable<int> Tuổi
		{
			get
			{
				return this._Tuổi;
			}
			set
			{
				if ((this._Tuổi != value))
				{
					this.OnTuổiChanging(value);
					this.SendPropertyChanging();
					this._Tuổi = value;
					this.SendPropertyChanged("Tuổi");
					this.OnTuổiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HourWork", DbType="Int")]
		public System.Nullable<int> HourWork
		{
			get
			{
				return this._HourWork;
			}
			set
			{
				if ((this._HourWork != value))
				{
					this.OnHourWorkChanging(value);
					this.SendPropertyChanging();
					this._HourWork = value;
					this.SendPropertyChanged("HourWork");
					this.OnHourWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeofEmployee", DbType="NVarChar(50)")]
		public string TypeofEmployee
		{
			get
			{
				return this._TypeofEmployee;
			}
			set
			{
				if ((this._TypeofEmployee != value))
				{
					this.OnTypeofEmployeeChanging(value);
					this.SendPropertyChanging();
					this._TypeofEmployee = value;
					this.SendPropertyChanged("TypeofEmployee");
					this.OnTypeofEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cua Hang]", Storage="_Cua_Hang", DbType="NChar(10)")]
		public string Cua_Hang
		{
			get
			{
				return this._Cua_Hang;
			}
			set
			{
				if ((this._Cua_Hang != value))
				{
					this.OnCua_HangChanging(value);
					this.SendPropertyChanging();
					this._Cua_Hang = value;
					this.SendPropertyChanged("Cua_Hang");
					this.OnCua_HangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
